version: 2
updates:
- package-ecosystem: elm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - Punie
  labels:
  - dependencies
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - Punie
  labels:
  - dependencies
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 3.10.1
    - 4.15.2
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.10.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
